# Generated by Django 3.1 on 2023-03-31 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='session_status',
        ),
        migrations.AddField(
            model_name='service',
            name='session_status',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
